<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-MUQUGSJ" name="com.a3hp.automationpracticee.framework.test.homepage.HomepageTest" tests="14" failures="8" timestamp="29 Oct 2018 16:35:36 GMT" time="2314.723" errors="0">
  <testcase name="validateHeaderSignInLink_HP" time="180.069" classname="com.a3hp.automationpracticee.framework.test.homepage.HomepageTest"/>
  <testcase name="validateHeaderSignInLink_HP" time="103.974" classname="com.a3hp.automationpracticee.framework.test.homepage.HomepageTest"/>
  <testcase name="validateGetSavingNowButton_HP" time="184.466" classname="com.a3hp.automationpracticee.framework.test.homepage.HomepageTest"/>
  <testcase name="validateGetSavingNowButton_HP" time="130.689" classname="com.a3hp.automationpracticee.framework.test.homepage.HomepageTest"/>
  <testcase name="validateSearchField_HP" time="81.429" classname="com.a3hp.automationpracticee.framework.test.homepage.HomepageTest"/>
  <testcase name="validateSearchField_HP" time="127.917" classname="com.a3hp.automationpracticee.framework.test.homepage.HomepageTest"/>
  <testcase name="validateHomepageSlider1_HP" time="147.407" classname="com.a3hp.automationpracticee.framework.test.homepage.HomepageTest">
    <failure type="java.lang.AssertionError" message="expected [https://www.prestashop.com/en?utm_source=v16_homeslider] but found [http://www.prestashop.com/?utm_source=v16_homeslider]">
      <![CDATA[java.lang.AssertionError: expected [https://www.prestashop.com/en?utm_source=v16_homeslider] but found [http://www.prestashop.com/?utm_source=v16_homeslider]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.a3hp.automationpracticee.framework.test.homepage.HomepageTest.validateHomepageSlider1_HP(HomepageTest.java:158)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- validateHomepageSlider1_HP -->
  <testcase name="validateHomepageSlider1_HP" time="194.997" classname="com.a3hp.automationpracticee.framework.test.homepage.HomepageTest">
    <failure type="java.lang.AssertionError" message="expected [https://www.prestashop.com/en?utm_source=v16_homeslider] but found [http://www.prestashop.com/?utm_source=v16_homeslider]">
      <![CDATA[java.lang.AssertionError: expected [https://www.prestashop.com/en?utm_source=v16_homeslider] but found [http://www.prestashop.com/?utm_source=v16_homeslider]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.a3hp.automationpracticee.framework.test.homepage.HomepageTest.validateHomepageSlider1_HP(HomepageTest.java:158)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- validateHomepageSlider1_HP -->
  <testcase name="validateHomepageSlider2_HP" time="201.293" classname="com.a3hp.automationpracticee.framework.test.homepage.HomepageTest">
    <failure type="java.lang.AssertionError" message="expected [https://www.prestashop.com/en?utm_source=v16_homeslider] but found [http://www.prestashop.com/?utm_source=v16_homeslider]">
      <![CDATA[java.lang.AssertionError: expected [https://www.prestashop.com/en?utm_source=v16_homeslider] but found [http://www.prestashop.com/?utm_source=v16_homeslider]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.a3hp.automationpracticee.framework.test.homepage.HomepageTest.validateHomepageSlider2_HP(HomepageTest.java:174)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- validateHomepageSlider2_HP -->
  <testcase name="validateHomepageSlider2_HP" time="65.786" classname="com.a3hp.automationpracticee.framework.test.homepage.HomepageTest">
    <failure type="java.lang.AssertionError" message="expected [https://www.prestashop.com/en?utm_source=v16_homeslider] but found [http://www.prestashop.com/?utm_source=v16_homeslider]">
      <![CDATA[java.lang.AssertionError: expected [https://www.prestashop.com/en?utm_source=v16_homeslider] but found [http://www.prestashop.com/?utm_source=v16_homeslider]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.a3hp.automationpracticee.framework.test.homepage.HomepageTest.validateHomepageSlider2_HP(HomepageTest.java:174)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- validateHomepageSlider2_HP -->
  <testcase name="validateHomepageSlider3_HP" time="78.672" classname="com.a3hp.automationpracticee.framework.test.homepage.HomepageTest">
    <failure type="java.lang.AssertionError" message="expected [https://www.prestashop.com/en?utm_source=v16_homeslider] but found [http://www.prestashop.com/?utm_source=v16_homeslider]">
      <![CDATA[java.lang.AssertionError: expected [https://www.prestashop.com/en?utm_source=v16_homeslider] but found [http://www.prestashop.com/?utm_source=v16_homeslider]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.a3hp.automationpracticee.framework.test.homepage.HomepageTest.validateHomepageSlider3_HP(HomepageTest.java:186)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- validateHomepageSlider3_HP -->
  <testcase name="validateHomepageSlider3_HP" time="211.714" classname="com.a3hp.automationpracticee.framework.test.homepage.HomepageTest">
    <failure type="java.lang.AssertionError" message="expected [https://www.prestashop.com/en?utm_source=v16_homeslider] but found [http://www.prestashop.com/?utm_source=v16_homeslider]">
      <![CDATA[java.lang.AssertionError: expected [https://www.prestashop.com/en?utm_source=v16_homeslider] but found [http://www.prestashop.com/?utm_source=v16_homeslider]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.a3hp.automationpracticee.framework.test.homepage.HomepageTest.validateHomepageSlider3_HP(HomepageTest.java:186)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- validateHomepageSlider3_HP -->
  <testcase name="validateHomepageCarouselBlocks_HP" time="335.991" classname="com.a3hp.automationpracticee.framework.test.homepage.HomepageTest">
    <failure type="java.lang.AssertionError" message="expected [[https://www.prestashop.com/en?utm_source=v16_homeslider, https://www.prestashop.com/en?utm_source=v16_homeslider, https://www.prestashop.com/en?utm_source=v16_homeslider, https://www.prestashop.com/en?utm_source=v16_homeslider, https://www.prestashop.com/en?utm_source=v16_homeslider]] but found [[http://www.prestashop.com/?utm_source=v16_homeslider, http://www.prestashop.com/?utm_source=v16_homeslider, http://www.prestashop.com/?utm_source=v16_homeslider, http://www.prestashop.com/?utm_source=v16_homeslider, http://www.prestashop.com/?utm_source=v16_homeslider]]">
      <![CDATA[java.lang.AssertionError: expected [[https://www.prestashop.com/en?utm_source=v16_homeslider, https://www.prestashop.com/en?utm_source=v16_homeslider, https://www.prestashop.com/en?utm_source=v16_homeslider, https://www.prestashop.com/en?utm_source=v16_homeslider, https://www.prestashop.com/en?utm_source=v16_homeslider]] but found [[http://www.prestashop.com/?utm_source=v16_homeslider, http://www.prestashop.com/?utm_source=v16_homeslider, http://www.prestashop.com/?utm_source=v16_homeslider, http://www.prestashop.com/?utm_source=v16_homeslider, http://www.prestashop.com/?utm_source=v16_homeslider]]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.a3hp.automationpracticee.framework.test.homepage.HomepageTest.validateHomepageCarouselBlocks_HP(HomepageTest.java:221)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- validateHomepageCarouselBlocks_HP -->
  <testcase name="validateHomepageCarouselBlocks_HP" time="270.319" classname="com.a3hp.automationpracticee.framework.test.homepage.HomepageTest">
    <failure type="java.lang.AssertionError" message="expected [[https://www.prestashop.com/en?utm_source=v16_homeslider, https://www.prestashop.com/en?utm_source=v16_homeslider, https://www.prestashop.com/en?utm_source=v16_homeslider, https://www.prestashop.com/en?utm_source=v16_homeslider, https://www.prestashop.com/en?utm_source=v16_homeslider]] but found [[http://www.prestashop.com/?utm_source=v16_homeslider, http://www.prestashop.com/?utm_source=v16_homeslider, http://www.prestashop.com/?utm_source=v16_homeslider, http://www.prestashop.com/?utm_source=v16_homeslider, http://www.prestashop.com/?utm_source=v16_homeslider]]">
      <![CDATA[java.lang.AssertionError: expected [[https://www.prestashop.com/en?utm_source=v16_homeslider, https://www.prestashop.com/en?utm_source=v16_homeslider, https://www.prestashop.com/en?utm_source=v16_homeslider, https://www.prestashop.com/en?utm_source=v16_homeslider, https://www.prestashop.com/en?utm_source=v16_homeslider]] but found [[http://www.prestashop.com/?utm_source=v16_homeslider, http://www.prestashop.com/?utm_source=v16_homeslider, http://www.prestashop.com/?utm_source=v16_homeslider, http://www.prestashop.com/?utm_source=v16_homeslider, http://www.prestashop.com/?utm_source=v16_homeslider]]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.a3hp.automationpracticee.framework.test.homepage.HomepageTest.validateHomepageCarouselBlocks_HP(HomepageTest.java:221)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- validateHomepageCarouselBlocks_HP -->
</testsuite> <!-- com.a3hp.automationpracticee.framework.test.homepage.HomepageTest -->
